---
version: "3"
services:
 devopsdb:
   container_name: containerapp
   image: shaikmustafa/valluri:dbimage
   ports:
     - "3306:3306"

 application:
   container_name: devopsdb
   image: shaikmustafa/valluri:appimage 
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
